services:
  short-url-client:
    build: .
    container_name: short-url-client
    network_mode: bridge
    environment:
      VIRTUAL_HOST: short-url-client.demo.weksik.ru
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: short-url-client.demo.weksik.ru
      LETSENCRYPT_EMAIL: ssl@weksik.ru
